### ISSUE TITLE
Jittering during typing

### ISSUE THREAD

**Issue by RenaudThoraval** [kisstkondoros/typelens#1]
Hi ! This extension is really cool and useful. But its behaviour when you type code should be different.  The references are recomputed after every keystroke. Their lines disappear and reappear continuously.
Space allocated above each method for their references should be reserved while we type or you may add a debounce delay before references updates. For example, you could refresh references 100 ms after the last keystroke.
I'll try to fix it and submit a PR if I have time.

Nice job !

Regards,

Renaud
(Sorry for my english, i'm not fluent.)

**Comment by kisstkondoros** [comment]
Hi,

Sorry for the inconvenience, it was a misused api call.
