### ISSUE TITLE
Add html usage to references for typescript classes that are angular2 components

### ISSUE THREAD

**Issue by mmc41** [kisstkondoros/typelens#10]
In Angular 2, the typescript classes with the @Component annotations can be used inside html. Hence, when viewing references for such classes, it would be nice if it can include references to usages inside html files.

**Comment by kisstkondoros** [comment]
You are absolutely right, but as I've stated already in the readme I can't do anything about it, if someone creates an Angular 2 extension for VS which provides the proper reference metadata, then my extension will pick that up. Until that I can't do anything about it 😞

**Comment by mmc41** [comment]
One approach would be to look for classes with  @Component annotation, extract the selector parameter (e.g. 'app-hello') and then do a search for all html files that contain tags with the selector (e.g. <app-hello.*>.*</app-hello>). I agree, this is not so easy.

**Comment by kisstkondoros** [comment]
Not just not easy, it is not the role of this extension. If I would implement it using some pattern recognition I would end up supporting it for the next decade. 😄 
There must be other, more talented people in the world who can implement it in the right way.
