### ISSUE TITLE
I'm getting double references

### ISSUE THREAD

**Issue by sean-mcmanus** [kisstkondoros/typelens#11]
VS Code 1.5.3. TypeLens 1.2.1, Win10.

When I enable the extension, I get 2 references. Is there a way to figure out what is going wrong? It only seems to repro for certain functions.

![doublereferences](https://cloud.githubusercontent.com/assets/19859882/18885902/7b11ee7a-84a2-11e6-9996-5c528f00e4b8.png)

**Comment by kisstkondoros** [comment]
Seems to be a typescript@2.0 problem, fix is on the way

**Comment by kisstkondoros** [comment]
Should be OK with v1.2.2

**Comment by sean-mcmanus** [comment]
Okay, thanks a lot.
