### ISSUE TITLE
References cause colorization errors

### ISSUE THREAD

**Issue by sean-mcmanus** [kisstkondoros/typelens#12]
Could be a VS Code bug. The gray color somewhat randomly bleeds into the lines below. Other users have reported this issue too (possibly with another another extension, not sure). The function name should be green in the picture.

![typelenscolor](https://cloud.githubusercontent.com/assets/19859882/18886643/9adc6688-84a5-11e6-8e11-c1776f91741c.png)

**Comment by kisstkondoros** [comment]
Thanks for reporting the problem.
Version 1.2.3 contains a fix for this issue.
