### ISSUE TITLE
Showing references on decorators

### ISSUE THREAD

**Issue by 19majkel94** [kisstkondoros/typelens#13]
This extensions is really helpful but it mistakenly checks references on decorators:

![2016-10-26 19_39_58-lista szybkiego dostepu dla visual studio code](https://cloud.githubusercontent.com/assets/10618781/19737552/37825680-9bb4-11e6-87e8-7177c4ea87b7.png)

You should check if it's a decorator and don't produce referencing count on them but on the property.

**Comment by kisstkondoros** [comment]
Thanks for reporting the issue, there was an issue with some index checking.
It should be fixed in version 1.2.4.
