### ISSUE TITLE
Add a way to exclude a language from having references provided

### ISSUE THREAD

**Issue by eamodio** [kisstkondoros/typelens#14]
That way languages like C# which are already provided by its own extensions could be excluded.

**Comment by kisstkondoros** [comment]
Fair enough!

A new option has been introduced:
> - typelens.skiplanguages
>   - Languages where the references should not be shown

Since the C# extension comes with a  built in reference lens functionality I've added 'csharp' to be excluded by default (however their reference lens are not that awesome as this one 😄  )

Should be possible to specify it like so:
```json
"typelens.skiplanguages": [
    "csharp"
]
```
