### ISSUE TITLE
TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by eamodio** [kisstkondoros/typelens#15]
I'm getting this error in the console:
```
TypeError: Cannot read property 'document' of undefined
    at /Users/eric/.vscode-insiders/extensions/kisstkondoros.typelens-1.3.0/out/src/extension.js:217:42
```

I think you just need add some protection [here](https://github.com/kisstkondoros/typelens/blob/master/src/extension.ts#L212) because `onDidChangeActiveTextEditor` can be fired with an `undefined` editor in certain cases.

**Comment by kisstkondoros** [comment]
Thank you! 1.3.1 is in the market!
