### ISSUE TITLE
Wrong positioning when ctrl click

### ISSUE THREAD

**Issue by SalvatorePreviti** [kisstkondoros/typelens#16]
When using ctrl+click to go to the definition, and more than one definition is found, the "peek code" preview is shown. With the typelens plugin enabled the window scroll away from the "code peek" view, making it off center.

**Comment by kisstkondoros** [comment]
Could you please elaborate the desired behavior? For me everything looks the same. I'm sure I've slept over some details... perhaps a gif would help.
Some more installation details might be useful:
Do you use the latest version of vscode?
Have you tried it with the insiders version as well?
What other extensions do you have installed?

**Comment by kisstkondoros** [comment]
ping

**Comment by kisstkondoros** [comment]
@SalvatorePreviti I'll close the ticket until you provide further information.
I suspect the extension has nothing to do with the actual problem, but maybe vscode itself does. If possible I'll even try to fix it in the vscode core as well. (once I'll know what was gone wrong)
