### ISSUE TITLE
Feature Request: Add functionality to toggle typelens on/off

### ISSUE THREAD

**Issue by rokoroku** [kisstkondoros/typelens#18]
I really love this extension. 
However, I feel a bit uncomfortable while writing code.

Could you add toggle feature that can be triggered with configurable shortcut?

**Comment by kisstkondoros** [comment]
Version 1.4.1 which includes the feature is in the market.
You can bind the new command like this:
```json
{
    "key": "ctrl+1",
    "command": "typelens.toggle",
    "when": "editorTextFocus"
}
```
