### ISSUE TITLE
changes color of method names

### ISSUE THREAD

**Issue by MattEllison** [kisstkondoros/typelens#19]
First of all great extension. Thank you for creating it.

~~Not a big deal but when its adding the references within my typescript files its altering the color of the method names which matches the text color for the references text above each method. Is there any way to control that?~~

Sorry I see how it works now. Didn't catch its because nothing was found. I guess the issue is that because I am using this with angular I have code in the html file that's referencing it.  However this works for me. Thanks!

Before TypeLens enabled
https://i.imgur.com/PH9FbDN.png

With Type Lens enabled
https://i.imgur.com/5BTxtbH.png

**Comment by kisstkondoros** [comment]
No problem :-) I'm glad you like it.
You can turn off the method name coloring by setting the "typelens.decorateunused" flag to false.
For reference:
https://github.com/kisstkondoros/typelens/blob/master/package.json#L52
