### ISSUE TITLE
TypeLens ignores its disabled settings

### ISSUE THREAD

**Issue by mutsys** [kisstkondoros/typelens#20]
Once TypeLens is installed, regardless of whether I set it to be disabled "always" or "workspace", it still gets loaded and I still see reference counts getting displayed.

**Comment by kisstkondoros** [comment]
Could it be that `"typescript.referencesCodeLens.enabled": true` is present in your settings.json? So that the typescript references are shown always?

Another possibility might be that you have to restart or at least reload (F1->reload window) vscode.
