### ISSUE TITLE
Handling React class methods

### ISSUE THREAD

**Issue by batjko** [kisstkondoros/typelens#23]
Hi there,

First of all, hats-off for the extension, very useful! :+1: 

I noticed that class methods, which in React are often implicit (i.e. are not explicitly called), get references as well, e.g.:

![image](https://user-images.githubusercontent.com/7287076/30537114-600156ee-9c60-11e7-9d5a-d85011a889e0.png)

Even into the `@types/react` typing inside node_modules:

![image](https://user-images.githubusercontent.com/7287076/30537138-73bef4ca-9c60-11e7-9336-0c116926004a.png)

I would like those to be ignored, ideally. I'm not sure if that's a bug or an enhancement request, but there you go.

Cheers.

**Comment by kisstkondoros** [comment]
I've introduced source blackboxing, I hope it'll be useful for Your use case.
You can add source files to the blackbox setting the configuration property `typelens.blackbox`.
e.g.
```json
"typelens.blackbox": [
    "**/node_modules/**"
]
```

Oh and typelens@1.5.0 is already available in the market ^^

**Comment by batjko** [comment]
Ah, that should do the trick for those cases.
I'll try it out asap and report back.

Thanks a lot! ;)

**Comment by batjko** [comment]
Is there any way of removing the annotations in the case of blackbox references?

In my use case above, there is really no point in having any:

![image](https://user-images.githubusercontent.com/7287076/30612298-f80ec4f0-9d7b-11e7-950b-7f6a3aeb18d4.png)

I tried setting the blackboxTitle to an empty string, but that doesn't prevent the annotation line from being inserted anyway, which then looks like an empty padded line.

**Comment by kisstkondoros** [comment]
Unfortunatelly no, the creation and resolution of the code lenses can only be done in two phases:
1. Provide positions - mustbe fast
2. Determine details - can be slow
Additionay I rely on the result of core commands of vscode (so that the extension is not limited to ts/js)

**Comment by batjko** [comment]
Ok, no worries. I'll just change the title to the same as "no references", which works just fine.

Thanks again!

**Comment by kisstkondoros** [comment]
You are welcome!
