### ISSUE TITLE
File scrolls down when refocused again

### ISSUE THREAD

**Issue by abdulkareemnalband** [kisstkondoros/typelens#24]
- VSCode Version: Code 1.16.1 64 bit (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
-Typelens:1.50

## Steps to reproduce

1. open two typescript files
2. Note file scroll postion
3. switch focus to another file (click on file's tab)
4. Switch back to first file
5. Note scroll position now (it will be scrolled down)

**Comment by kisstkondoros** [comment]
Thanks for the issue report!

I have no influence on how the scroll position is restored, please refer to https://github.com/Microsoft/vscode/issues/32397 for further progress / details.

**Comment by eteisman** [comment]
For me the issue only happens when the setting "typescript.referencesCodeLens.enabled" is set to true.
Disabling referenseCodeLens resolves the issue.
