### ISSUE TITLE
Not recognizing angular references.

### ISSUE THREAD

**Issue by hiagodotme** [kisstkondoros/typelens#29]
Hello everyone, I do not know if I can consider it as an issue or not. But I am using the plugin in my Visual Studio Code, and since now I leave my congratulations for the extension. But it can not recognize references in the templates / html of the Angular.

I know it was made for TypeScript and not for frameworks (like the angular), but I believe if I could see the HTML references or any other file (as an option) it would be very useful for the community.

**Comment by kisstkondoros** [comment]
I can't do anything about it unfortunately.
See #25 for more details.

**Comment by hiagodotme** [comment]
Thanks for the answer @kisstkondoros.
