### ISSUE TITLE
Class called from another file

### ISSUE THREAD

**Issue by Aljduites** [kisstkondoros/typelens#30]
If I call a class from another file, would the class show the reference?

**Comment by kisstkondoros** [comment]
Yes, the extension shows the amount of references for Methods, Functions, Properties,Classes and Interfaces.

e.g.
![screenshot 2018-09-17 19 38 16](https://user-images.githubusercontent.com/14231157/45639808-42f30280-bab1-11e8-9089-181734347226.png)
