### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by ovidius72** [kisstkondoros/typelens#31]
Hi thanks for this great extension. I'm having a lot of this messages in the output window.
I'm using the latest 1.29.0-insider version. It's a typescript project.

`[renderer1] [error] Cannot read property 'filter' of undefined: TypeError: Cannot read property 'filter' of undefined
	at vscode_1.commands.executeCommand.then.symbolInformations (/Users/antonio/.vscode-insiders/extensions/kisstkondoros.typelens-1.6.1/out/src/extension.js:106:22)
	at <anonymous>`

**Comment by kisstkondoros** [comment]
Thanks for the issue report!

Could you please provide more information, since I can't reproduce the problem locally.
The problem is strange since in theory the symbolInformations are provided by vscode and the promise should not resolve to undefined (IMO).
```javascript
commands.executeCommand<SymbolInformation[]>("vscode.executeDocumentSymbolProvider", document.uri).then(symbolInformations => {
...
});
```
Which makes me wonder that it could be that there is another extension installed at your system which violates this "contract".

If you couldn't add any further details I'm going to fix it by adding a null check, but I would like to fix it in a proper way and so any details are appreciated.

**Comment by roman-petrov** [comment]
It seems we have the same problem after VSCode update to 1.28.0: the same message in "Log (Window)" and the extension shows references only for classes, not for methods.

**Comment by ovidius72** [comment]
> Thanks for the issue report!
> 
> Could you please provide more information, since I can't reproduce the problem locally.
> The problem is strange since in theory the symbolInformations are provided by vscode and the promise should not resolve to undefined (IMO).
> 
> ```js
> commands.executeCommand<SymbolInformation[]>("vscode.executeDocumentSymbolProvider", document.uri).then(symbolInformations => {
> ...
> });
> ```
> 
> Which makes me wonder that it could be that there is another extension installed at your system which violates this "contract".
> 
> If you couldn't add any further details I'm going to fix it by adding a null check, but I would like to fix it in a proper way and so any details are appreciated.

I'm sorry. I've searched in the output window and in the dev tool console but couldn't find additional info about the error.

**Comment by roman-petrov** [comment]
I am not sure if this can help: My VSCode version info is:

Version: 1.28.0 (user setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

To reproduce I just launch VSCode and open "Log(Window)" in "Output" panel, here is a screen shot
![image](https://user-images.githubusercontent.com/18419515/46691262-23ad4800-cc0d-11e8-88e1-df6d8dbc0a65.png)
