### ISSUE TITLE
Not working anymore VS code ver: 1.29.1

### ISSUE THREAD

**Issue by Sampath-Lokuge** [kisstkondoros/typelens#32]
Hi,

This is not working at all for me. Please let me know what should I do here. I just installed it and reload the editor. Since it didn't work I have to restart the VS code too. No luck yet.Any clue?

Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

![vs](https://user-images.githubusercontent.com/5206526/49067357-de3eeb80-f249-11e8-98c6-fdfd387ea5cc.png)

**Comment by Sampath-Lokuge** [comment]
Now it is working fine. It took some time to work. No issues now. Thanks for the great extension.

**Comment by RamonBalthazar** [comment]
What did you do to make it work?

**Comment by Sampath-Lokuge** [comment]
@RamonBalthazar Sometimes it takes time to show. Sometimes you need to restart the VS Code.
