### ISSUE TITLE
Add a find reference from templates

### ISSUE THREAD

**Issue by Sampath-Lokuge** [kisstkondoros/typelens#33]
Feature request:

This is a great extension. But I have one suggestion. Can you add a find reference from templates? i.e. .ts methods can be referenced by .html templates. Now it shows `no reference found for ...`

**Note:** If you can't do this right now please change the above text like so `0 references`

**Comment by kisstkondoros** [comment]
Thanks for the feedback, I understand that a lot of users are requesting this feature (https://github.com/kisstkondoros/typelens/issues?utf8=%E2%9C%93&q=template) but it is out of reach for this extension.
(This is also clearly stated in the readme: https://github.com/kisstkondoros/typelens/blob/master/README.md#typelens)

For the text change:
One can change the message shown by setting a configuration property:
```json
"typelens.noreferences": "0 references"
```

If You ask me it is just as misleading as the current one in such a case...

**Comment by Sampath-Lokuge** [comment]
That works. Thanks a lot.

**Comment by kisstkondoros** [comment]
You are welcome!
