### ISSUE TITLE
Multiple declarations on the same line breaks reference count

### ISSUE THREAD

**Issue by Sleeckx** [kisstkondoros/typelens#35]
Having more than one declaration on the same line breaks the reference count.

![image](https://user-images.githubusercontent.com/2143495/52405771-59cfdb00-2acc-11e9-9d9f-34b4940f75c5.png)

![image](https://user-images.githubusercontent.com/2143495/52405789-681df700-2acc-11e9-9e6c-5a49e09be0c8.png)

**Comment by kisstkondoros** [comment]
Version 1.6.5 was just released with a fix for this :fireworks:
