### ISSUE TITLE
Typescript interfaces are hard to read

### ISSUE THREAD

**Issue by sgtwilko** [kisstkondoros/typelens#36]
When writing typescript interfaces decorating the fields inside the interface causes half the interface to be made of usage count decorators.

Would it be possible to either:
Have an option to disable the decorators inside the interface
Or, show the information to the right so that interface isn't made longer.

**Comment by kisstkondoros** [comment]
Thanks for reaching out!

Option 1. :
the extension knows little about the language, it relies on the commands vscode provides. (`vscode.executeReferenceProvider` and `vscode.executeDocumentSymbolProvider`)

Option 2. :
the information is shown as a codelens, and as such it has 2 resolution steps:
1. `provideCodeLenses`
2. `resolveCodeLens`
I could barely do the same with some inline decoration approach (in fact I do have something similar for another extension, and it's a mess which I don't want to replicate here).

Sorry for letting you down, but I have no plans supporting either of these options.
