### ISSUE TITLE
Add Language support

### ISSUE THREAD

**Issue by Jonasdero** [kisstkondoros/typelens#39]
Im writing a test automation in SahiPro, which has .sah files
The syntax is basically javascript. 
Is it possible to scan through all files of my workspace and show the references?

**Comment by kisstkondoros** [comment]
As it is stated in the readme, the extension does not provides any feature for languages on its own, the necessary information should be provided via the standard vscode api.

I'm sorry but I couldn't support this use case for now.
If someone integrates the .sah file extension with the javascript language support somehow, then it would be possible for sure, but as I saw there is no such an extension yet.

I know it is drastical but if it is "basically javascript" why doesn't it have that as an extension?

For now I'm closing this, but feel free to reopen / open a new one.

**Comment by Jonasdero** [comment]
Okay I changed the file extension to .js and the software still recognizes it! Thanks
