### ISSUE TITLE
Ember.js methods are grayed out when they have the async keyword on them

### ISSUE THREAD

**Issue by havremunken** [kisstkondoros/typelens#40]
Hi there,

Thanks for an awesome plugin, I have used in in a TypeScript project and it has worked well. However, when using it in a javascript-based Ember.js (3.10) project, I noticed behaviour which seems weird. I have functions inside Ember objects (so far does not seem to matter if I am in a controller, component, service, ...) - when I add the "async" keyword to the function definition, syntax highlighting disappears from VS Code. It does reappear while I am actively typing in the file in question, but as soon as I stop typing again, the function is grayed out.

It does not seem to matter if codelens is picking up any references to this function or not.

As soon as I disabled typelens, the problem went away. That of course does not mean that typelens is the problem, only that this is the way it manifests.

If anything needs to be tested, please let me know, and I will do so. It is very easy to reproduce in my current dev environment.

Thanks!

**Comment by havremunken** [comment]
I just found that this also happens when editing a pure, non-Ember-related javascript file. In this case a Fastify route. As soon as the async keyword appears, the function body is greyed out. So Ember seems not to be part of the equation.

**Comment by kisstkondoros** [comment]
Thanks for reporting the problem!

v1.7.0 was just released, I hope it will solve this problem for you!
If not, feel free to open a new issue.
