### ISSUE TITLE
[feature] add option to hide no reference found msg

### ISSUE THREAD

**Issue by ctf0** [kisstkondoros/typelens#42]
i can remove the msg, but the decorated line still there.

so is there away to have an option to disable the whole info "msg & line" when there is no reference found ?

ref https://github.com/kisstkondoros/typelens/issues/37

**Comment by kisstkondoros** [comment]
It is technically not possible to achieve this (at the moment). The technique used here is about determining document symbols and create codelens for them, the second step is to fill these with information. As you can see the first step already creates the placeholders and there is no way to remove them.

Of course I could hack around the system and manage my own editor state for this particular case, but I'm not willing to and I hope you understand that.

Sorry for the inconvenience.

**Comment by ctf0** [comment]
isnt it possible to check first for the symbol codelens info and based on it either create the placeholder or not ?

**Comment by kisstkondoros** [comment]
The number of references are determined in the second step, so no, it isn't.
