### ISSUE TITLE
No lens shown for values or types in TypeScript

### ISSUE THREAD

**Issue by orokanasaru** [kisstkondoros/typelens#43]
![image](https://user-images.githubusercontent.com/5751627/63714069-d078bf80-c7f5-11e9-9a20-81966d6c85a2.png)

**Comment by kisstkondoros** [comment]
I'll close this as the API provides us no way of knowing that `const bar` and `type Bar` are top level symbols.

What we do know about them is the symbol kind which is `constant` and `variable` respectively. If I would enable the reference lens to be shown for both, then the reference lens would be shown also inside method bodies which is extremely annoying.

Perhaps the reference lens is not the best visualization afterall...

**Comment by ctf0** [comment]
@kisstkondoros does this still the case with the new builds of vscode ?
