### ISSUE TITLE
No references found for module.exports

### ISSUE THREAD

**Issue by orokanasaru** [kisstkondoros/typelens#44]
![image](https://user-images.githubusercontent.com/5751627/63715171-16368780-c7f8-11e9-8ea3-d033d0410093.png)

For the `2 references`, one is the declaration itself, which probably shouldn't count. The other is where it is required, which is the only place I want to see. 

The `no references found for module.exports` part is just confusing.

**Comment by kisstkondoros** [comment]
Thanks for reporting this, the fix is on the way.

**Comment by kisstkondoros** [comment]
Please check typelens@1.9.2, it should contain the fix for this problem.
