### ISSUE TITLE
TypeLens causing highlighting issues in PowerShell files

### ISSUE THREAD

**Issue by rjmholt** [kisstkondoros/typelens#46]
From https://github.com/PowerShell/vscode-powershell/issues/2293.

Enabling CodeLens with the PowerShell extension and installing the TypeLens extension causes highlighting issues that look like this:

![Highlighting all goes grey after several lines](https://user-images.githubusercontent.com/37800313/68470174-7348b380-0213-11ea-865c-2bedac506a0c.png)

The PowerShell extension doesn't touch highlighting, but it looks like this is a bad interaction between the two extensions.

It might be worth:

1. Seeing what causes this to happen specifically with the PowerShell extension (if we're generating some bad metadata that causes this, we should fix it).
2. Working out if it's feasible to only enable TypeLens in files of particular language modes or file extensions.

**Comment by kisstkondoros** [comment]
Thanks for the issue report, and sorry for the inconvenience.

1. I don't have the time to test it now (I would need to install a bunch of tools to test it on linux)
2. It is already possible to selectively disable the extension for given languages using the settings ```typelens.skiplanguages```

My assumption (when I've implemented this extension) was that reference counts can be retrieved reliably by two vscode commands ```vscode.executeDocumentSymbolProvider``` and ```vscode.executeReferenceProvider``` (the first provides the input for the second command).

I suppose the other reference counting (which can be seen as the other codelens) was also done based on these (perhaps with a bit more metadata), so I'm sure my extension is the cause, but I have the feeling that this can not be solved in a language independent way on my side at the moment.

If you think I can release a new version with a predefined exclusion for powershell (as the functionality would be duplicated anyway...)

**Comment by rjmholt** [comment]
/cc @SimonHounsell you might be able to use the setting mentioned above to solve the issue you're seeing. For reference, do you see it with any other languages?

@kisstkondoros thanks for getting back to me. I don't know what the particular APIs/parameters of those VSCode commands are, but if the idea is for this extension to grey-out unreferenced (or referenced, but unreachable) code then it seems like it's doing its job and correctly greying-out PowerShell code that the PowerShell extension isn't finding references to (in some cases incorrectly, in other cases because it can't be statically determined).

If so, I don't think there's anything to be fixed in TypeLens. There's a small fix to be made in PowerShell, but in general users should configure `typelens.skiplanguages` to exclude PowerShell if they find it's determining code to be unreachable, since PowerShell's dynamic scope and module path concepts make that much harder (and impossible in general) to determine statically.

If you agree, I'll leave you to close the issue as resolved.

**Comment by SimonHounsell** [comment]
> /cc @SimonHounsell you might be able to use the setting mentioned above to solve the issue you're seeing. For reference, do you see it with any other languages?
> 
> @kisstkondoros thanks for getting back to me. I don't know what the particular APIs/parameters of those VSCode commands are, but if the idea is for this extension to grey-out unreferenced (or referenced, but unreachable) code then it seems like it's doing its job and correctly greying-out PowerShell code that the PowerShell extension isn't finding references to (in some cases incorrectly, in other cases because it can't be statically determined).
> 
> If so, I don't think there's anything to be fixed in TypeLens. There's a small fix to be made in PowerShell, but in general users should configure `typelens.skiplanguages` to exclude PowerShell if they find it's determining code to be unreachable, since PowerShell's dynamic scope and module path concepts make that much harder (and impossible in general) to determine statically.
> 
> If you agree, I'll leave you to close the issue as resolved.

I can confirm that adding the `typelens.skiplanguages` setting resolves the issue. I don't recall seeing this issue with any other languages.

Thank you very much for all your support with this - much appreciated!

**Comment by SimonHounsell** [comment]
> For reference, do you see it with any other languages?

I've now observed a similar issue with TypeScript files and have opened [an issue](https://github.com/kisstkondoros/typelens/issues/47) accordingly.
