### ISSUE TITLE
Remove CodeLens in keybindings.json

### ISSUE THREAD

**Issue by Denis-net** [kisstkondoros/typelens#48]
Hi @kisstkondoros ! 😊👋🏼

Could you remove typelens in `%appdata%\Code\User\keybindings.json` ?
Because given that it will never find anything, it makes difficult to read, expecially with some themes, the underlying bindings:

![immagine](https://user-images.githubusercontent.com/45769702/74082379-958fde80-4a59-11ea-938e-b59d6eda26d5.png)

Btw, this extension works with JSON files too ?
How ?

Thanks

**Comment by kisstkondoros** [comment]
Fair enough, I've fixed this in the latest version (1.9.4).

The reason for having it in JSON files is simple: it is shown everywhere if the endpoints provide any data. I suspect that the language support for these files (JSON with comments, these are not even simple JSON files) are backed by TypeScript too...

**Comment by Denis-net** [comment]
Works like a charm.
Thank you !

> The reason for having it in JSON files is simple: it is shown everywhere if the endpoints provide any data

Understood 👍🏼

> I suspect that the language support for these files (JSON with comments, these are not even simple JSON files) are backed by TypeScript too...

I see it: the extension is .json but comments are allowed.
Moreover VSCode treats this file differently since it displays that button in it.

Thank you,
Have a nice day ! 😊👋🏼
