### ISSUE TITLE
UI feedback

### ISSUE THREAD

**Issue by gregveres** [kisstkondoros/typelens#49]
Hi, I generally like the extension, but I find that I am gradually turning off features and I think I am on my way to disabling it altogether. 

First,  I set typelens.decorateunusedto false and I ran with it for a few more days.
Then I looked for a way to disable it for data members of a class but I now see that there isn't a way to do that, so I am jumping directly to disabling the extension. 

I find the extra lines with X references to be too intrusive. It really wrecks the flow of the code and it makes it really hard to read. It could be the theme that I am using because the reference is the same colour as some of the variable names. But more than that, I think it just bloats the view, obscuring the really important stuff with much less useful information. 

The number of references is useful, but not all the time. I would suggest thinking about a different way to present the information. I haven't tried to mock anything up but just thinking quickly, I wonder if there was some dot in front of the object that was green if there were references and red if there were no references. Then if you clicked on it, the same thing would happen as clicking on the X references string now. I really like the popup!

The advantage would be something that is much less intrusive and wouldn't double the number of lines that my code takes up.

**Comment by kisstkondoros** [comment]
Thanks for the feedback and sorry for the late answer.

I'm not planning to extend the feature set of this extension anymore.

PR's are welcomed of course.
