### ISSUE TITLE
"No references found" ?

### ISSUE THREAD

**Issue by mmc41** [kisstkondoros/typelens#5]
Love that I can see references with this tool. However, what using it, I see tree reference counts for classes - one of them is "No references found". What does each mean (and the first in particular) ?

![screen shot 2016-09-19 at 21 38 27](https://cloud.githubusercontent.com/assets/17993/18646367/79175cd2-7eb1-11e6-9e60-fbbee8b4573c.png)

**Comment by kisstkondoros** [comment]
The first one should be the module references, this caused an annoying jump while type problem, so I got rid of it,..
The second one should be the amount of references to the interface "Category".
About the third one I have no idea 😄 

Please retest it with the latest version: 1.2.0 should be in the market now 🎆

**Comment by mmc41** [comment]
Thanks - works fine now + only two reference counts shown for all classes (the same though - not sure what the diff is supposed to be)
