### ISSUE TITLE
Does not work in SCSS

### ISSUE THREAD

**Issue by parloti** [kisstkondoros/typelens#50]
It simply doesn't show references in scss files, although it does in typescript files.

![image](https://user-images.githubusercontent.com/9643115/77653418-f0c95200-6f6f-11ea-9eaf-118ca64dc3bd.png)

**Comment by kisstkondoros** [comment]
Thanks for reaching out!

It shows what the language server retruns: e.g. references for mixins.
As long as the language server implementation does not returns references for e.g. selectors it will remain incomplete. It is a known limitation of this extension, as it relies on other parts of vscode (provided by vscode itself or other extensions).

I'll close this issue, as I have no plans to provide this kind of reference lookups, as it is the job of (in this case) the SCSS language server.
