### ISSUE TITLE
Could you please explain why I got 0 references ?

### ISSUE THREAD

**Issue by algoritmus** [kisstkondoros/typelens#51]
Hello,

I am using ur extension and I just don't get why it shows 0 reference for me in this particular case.

Would you be so kind and explain me the reason ?

Many thanks in advance

Attila

![stack](https://user-images.githubusercontent.com/14004887/78019320-c7356f80-734f-11ea-995f-46d6f3173247.png)

**Comment by kisstkondoros** [comment]
Probably because `this` is an ambigious reference, depending on the call mechanism it can be different, e.g. the b function is called with t.b.apply({}). I got your point, it should be shown, but the references are not collected by the extension.
