### ISSUE TITLE
no references found for <unknown>

### ISSUE THREAD

**Issue by roojay520** [kisstkondoros/typelens#53]
vscode version: 1.45.1 
typescript version 3.9.2

BUG: editor color failure

![image](https://user-images.githubusercontent.com/11495164/82172897-20f0f980-98fe-11ea-8cc8-c3266935d30f.png)

**Comment by kisstkondoros** [comment]
Should be fixed in the latest version (v1.9.6)

**Comment by kisstkondoros** [comment]
Thanks for reporting the issue!
