### ISSUE TITLE
Font size setting?

### ISSUE THREAD

**Issue by przemekkwl** [kisstkondoros/typelens#57]
Hi, 
Is it possible to add setting to change font size for references? From my perspective forts are too big, and I cannot find any possibility to change it. (change only font with references counter) 

![image](https://user-images.githubusercontent.com/31653462/89942109-4307c880-dc1c-11ea-847d-e843cc2a4206.png)

**Comment by kisstkondoros** [comment]
The extension is using a standard mechanism offered by vscode, unfortunately there is no way to change it.
The related issue where the progress can be tracked is https://github.com/Microsoft/vscode/issues/16038

**Comment by przemekkwl** [comment]
Thanks for quick response!

**Comment by kisstkondoros** [comment]
You are welcome!
