### ISSUE TITLE
How to disable extension for multi-element selectors?

### ISSUE THREAD

**Issue by mystiquewolf** [kisstkondoros/typelens#63]
This selector of p, li looks really bad when broken into separate lines IMO. Is is actually normal for this extension to add these "references" lines in plain-old CSS files?
![Screenshot_20210508_120426](https://user-images.githubusercontent.com/16529989/117533492-d88e8800-aff5-11eb-9fde-8ef860fb5bfe.png)

**Comment by kisstkondoros** [comment]
Yes it is normal, you can turn it off though by the setting `typelens.skiplanguages`.
