### ISSUE TITLE
what editor, font and theme used in the below screen short

### ISSUE THREAD

**Issue by nepolean2** [kisstkondoros/typelens#64]
![image](https://user-images.githubusercontent.com/29598633/126679918-0db30f3f-e9fe-4d84-8d8e-11d7727ab63d.png)
https://marketplace.visualstudio.com/items?itemName=kisstkondoros.typelens&ssr=false#overview

I know it's like a silly thing to create an issue for this, but I liked it so want to know and use the same. Thank you

**Comment by kisstkondoros** [comment]
I think it is this one https://marketplace.visualstudio.com/items?itemName=rokoroku.vscode-theme-darcula
