### ISSUE TITLE
Disable for .eslintrc.js

### ISSUE THREAD

**Issue by rtojagic-fluxon** [kisstkondoros/typelens#65]
Hey, is there a way to disable plugin for specific files? For example in my .eslintrc.js config file it will gray out the whole file because nothing in there has references.. I tried blackboxing it but it will still not work. Thanks in advance!

**Comment by jerone** [comment]
Wondering the same thing. For test files for example.

Maybe with an inline comment:
```js
// typelens disable-file
```

**Comment by kisstkondoros** [comment]
Added in typelens v1.10.0

Usage:
```
{
  "typelens.exclude": ["**/.eslintrc.js"]
}
```
