### ISSUE TITLE
Crazy idea 

### ISSUE THREAD

**Issue by mmc41** [kisstkondoros/typelens#7]
Any plans to support showing git information (who/when changed) alongside the reference counts like in Visual Studio ? :-)

![codelens-for-visual-studio-2013-rc](https://cloud.githubusercontent.com/assets/17993/18658923/24452c60-7f07-11e6-97f1-e45bd1e209c8.jpg)

**Comment by kisstkondoros** [comment]
There is a promising extension already for this: https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens

**Comment by mmc41** [comment]
And even better - the extension seems to work fine with yours :-)

**Comment by mmc41** [comment]
FYI: [Screenshot of the happy result in this tweet](https://twitter.com/41concepts/status/769598613769060352)
