### ISSUE TITLE
TypeLens Does Not Find References for ViewChild Decorator in Angular Component

### ISSUE THREAD

**Issue by nxpatterns** [kisstkondoros/typelens#76]
TypeLens extension fails to locate references to a ViewChild property within an Angular component, despite its usage in the corresponding component template.

**Scenario:**

An Angular component defines a `ViewChild` property to interact with a child component, as demonstrated in the simplified code snippet below:

```typescript
export class ExampleComponent {
  @ViewChild('exampleRef') exampleRef: CustomComponentType | undefined;
}
```

This property is then referenced in the component's template like so:

```html
<custom-component #exampleRef></custom-component>
```

**Expected Behavior:**

TypeLens should identify and display references to the ViewChild property from the template, indicating where it is being used.

**Actual Behavior:**

TypeLens does not show any references to the ViewChild property when hovering over or near the property declaration in the TypeScript file. This occurs despite the clear usage of the property within the template file.

**Environment:**

Angular version: v17.2.2
TypeLens version: v1.10.0
Visual Studio Code version: v1.87.2 

**Additional Context:**

This issue seems to affect the discovery of template references for properties decorated with @ViewChild, potentially limiting the utility of TypeLens in Angular projects.

I am looking for guidance on whether this is a known limitation, a bug, or if there are any recommended workarounds to enable reference discovery for such scenarios. Any assistance or updates to enhance TypeLens's functionality with Angular templates would be greatly appreciated.

**Comment by kisstkondoros** [comment]
See readme

**Comment by nxpatterns** [comment]
Dear @kisstkondoros 

I recently reached out regarding an issue with the TypeLens extension not recognizing ViewChild references in Angular templates. I appreciate your direction to the README. I’ve carefully reviewed it but couldn't find a solution relevant to this Angular-specific scenario.

If I've overlooked something in the documentation, could you kindly point me specifically to the section that addresses this issue? Your expertise would greatly help not just me but potentially others facing similar challenges. Your quick closure of the issue felt dismissive, and as someone keen on supporting your work (even financially), I was hoping for a more collaborative approach.

Thank you for considering my request for a more detailed response. Your work is greatly valued, and I believe clearer communication could benefit the community surrounding your project.

**Comment by kisstkondoros** [comment]
This issue came up multiple times in the past. The most recent I believe is #56.

To sum it up:
This extension is built on top of the result of references returned by standard vscode commands. If the given framework / related LSP does not integrate correctly to it references will not show up.

As implementing framework specific workarounds would blew up the complexity of this extension, I decided not to do it.

Besides, the built-in reference lens support in vscode made this extension more or less obsolete (at least for typescript sources).

**Comment by nxpatterns** [comment]
Thank you @kisstkondoros for your detailed response and for shedding light on this matter.  

It's noteworthy that the built-in reference lens support in VSCode fails to display references in Angular components (TypeScript) that originate from Angular templates (HTML). 

This leaves your extension as the singular, effective solution on the market, with the exception of its inability to locate references to ViewChild Decorators. 

Would there be an opportunity for me to assist in resolving this limitation?

**Comment by kisstkondoros** [comment]
I'm afraid this can only be done by implementing the relevant APIs in https://github.com/angular/vscode-ng-language-service/
