### ISSUE TITLE
Parsing errors in IIFE and member functions

### ISSUE THREAD

**Issue by con-ssc** [kisstkondoros/typelens#8]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.10586
- TypeLens 1.2.0

Seems like there are some problems during finding functions signatures.
 
![image](https://cloud.githubusercontent.com/assets/8189808/18702306/63d9ddc8-7fe1-11e6-8048-f66039fd8184.png)
![image](https://cloud.githubusercontent.com/assets/8189808/18702311/6b7a79e8-7fe1-11e6-940a-07b3d1d01e46.png)

**Comment by kisstkondoros** [comment]
Thanks for the bug report!

v1.2.1 was just published to address this. 🎆
