### ISSUE TITLE
Too many references shown

### ISSUE THREAD

**Issue by mmc41** [kisstkondoros/typelens#9]
As the example show, using the latest version I besides the expected references, I also get reference counts shown for one of the arguments to my constructor and for a arrow functions (they should not be shown). The reference count for the arrow function is even wrong showing 2 references where there is only one. 

![screen shot 2016-09-21 at 20 36 15](https://cloud.githubusercontent.com/assets/17993/18724099/70a5b716-803b-11e6-85cf-98b1e5f218e4.png)

**Comment by kisstkondoros** [comment]
v1.2.1 is published which contains a fix to exclude anonym functions from the results.

> reference counts shown for one of the arguments to my constructor
around the constructor I think you can see the references for the two private fields

> arrow functions
the mentioned fix should solve this as well

Sorry for the inconvenience and thanks for the bug reports!
Keep them coming 😄

**Comment by mmc41** [comment]
Thanks for the  quick update. It is better, but I think the references for private fields look confusing in the way they are displayed. Can they be properly formatted (for reference what does Visual Studio do here)?

Also, I think nested functions should properly be excluded. For instance in this example, the categoryInUse helper function is nested inside a anonymous function. Possibly, it could be interesting to see if there is 0 or <>1 references but otherwise it does not provide useful info.

![screen shot 2016-09-23 at 10 01 07](https://cloud.githubusercontent.com/assets/17993/18778529/13a70caa-8175-11e6-9147-a27ce6198f98.png)

**Comment by mmc41** [comment]
@kisstkondoros Apparently, I am not allowed to reopen this issue - as I recall some repos allow is. Is that on purpose?

**Comment by kisstkondoros** [comment]
IMO it is perfectly valid to show reference lens for categoryInUse, even though it is inside a lambda function.

To be honest I have no idea why do you have multiple reference lens e.g. around getTreeRoot or categoryInUse...

Could you please provide an open source repo as reference where You can reproduce this behaviour?

**Comment by mmc41** [comment]
The reason I would like reference lens to be removed in this case is because it is not possible to refer to the categoryInUse function from the outside. So it is just adding unnecessary info (~noise). But it is a matter of taste. There is nothing wrong with the example as such.

**Comment by kisstkondoros** [comment]
Typescript@2.0 caused the references to be duplicated sometimes, that was fixed, please try the new version 1.2.3 😄
